# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 93ef4569c38a7fdc34601898585dae6851f03ceb74563494470adabf5786e44a7cce8f16d08211442b72427d60ae01890a4c9a5771a9d80c22ae9fa8ab745d28

test:
  secret_key_base: e8535a408fc2f9fbdca1e522693f20764eeaa7486874fe526c4d43c5c8638e700f7934bff006ce7b629ac1a7415f55b907ffeb1715cb87d2dd609404629552f0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
